name: learn-github-actions
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: '14'
      - run: npm install
      - run: npm deploy
